### ISSUE TITLE
install_libs.sh errors

### ISSUE THREAD

**Issue by BK-Yoo** [MysterionRise/mavenized-jcuda#13]
Hi, when I execute your 'install_libs.sh' file, it omits error like this,

[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'deploy'.
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO]    task-segment: [deploy:deploy-file](aggregator-style)
[INFO] ------------------------------------------------------------------------
[INFO] [deploy:deploy-file {execution: default-cli}]
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Missing group, artifact, version, or packaging information
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Thu Feb 11 19:20:02 KST 2016
[INFO] Final Memory: 9M/481M

My develop environment is
[os] ubuntu 14.04 LTS
[java] 1.8
[maven] 2.2.1

I am very curious about how you deployed this 'so', 'dylib' ... files.
Because now I am trying to make my 'thrift' files as you made on 'repo' directory.
Thank you for great project.

**Comment by MysterionRise** [comment]
Hello, thanks for your question. It's a bit unclear what you tried to do
with this shell script. It should be used only if you 100% understands
what's going on :)

Regarding your environment - I doubt it will work with Maven 2. All stuff
was done under Maven 3.

Please let me know, how I could help you.

2016-02-11 11:28 GMT+01:00 BK Yoo <notifications@github.com>:

**Comment by BK-Yoo** [comment]
Thanks for reply.
All your code and instruction of 'README' works fine.
But I am curious about repo directory.
In this directory, there is many 'maven-metadata.xml', and md5, sha1.
Of course many cuda library have 'md5', 'sha1' and pom files.
As I know, this files are created automatically when maven deploy was executed.
I understood that 'install_libs.sh' which is in 'repo' directory made this happen.
So I executed 'install_libs.sh' but I got errors as I told you.

What I want you to learn and understand is how to deploy those files by mvn deploy:deploy-file command.
The only example I found on google is this project, so If you don'y mind, could you tell how things happen?
