### ISSUE TITLE
JCuda10???

### ISSUE THREAD

**Issue by Charele** [MysterionRise/mavenized-jcuda#20]
We need JCuda10!!!!!!!!!!!!!!!!!

**Comment by MysterionRise** [comment]
@Charele thanks for your interest in the project, but I'm afraid I stopped maintaining it after creator of JCuda (@jcuda ) started to push JCuda libs to Maven central (as some people recommended to do :) )

For more information - take a look here - https://github.com/jcuda/jcuda-main/blob/master/USAGE.md

**Comment by jcuda** [comment]
@Charele Also note that JCuda 10.0.0 is already in Maven Central (I still have to update the README and Website, though - just replace the version number `0.9.2` with `10.0.0`)
