### ISSUE TITLE
OSX 10.9.4 UnsatisfiedLinkError

### ISSUE THREAD

**Issue by myxibrium** [MysterionRise/mavenized-jcuda#3]
I followed the instructions but still getting an error. I installed Cuda version 6.0.37, the jcuda.version property is 0.6.0, mvn clean package runs without error, generates the files listed below. mvn exec:exec fails with the stacktrace pasted below. The file names do not match up, and it's trying to load from "/lib" folder? So I tried pasting the files into "/lib" but same error. Please help!

My target/lib directory contains these files:

> jcublas.jar
> libJCublas2-mac-x86_64.dylib
> jcuda.jar
> libJCudaDriver-mac-x86_64.dylib
> jcufft.jar  
> libJCudaRuntime-mac-x86_64.dylib
> jcurand.jar
> libJCufft-mac-x86_64.dylib
> jcusparse.jar 
> libJCurand-mac-x86_64.dylib
> libJCublas-mac-x86_64.dylib
> libJCusparse-mac-x86_64.dylib

Stack trace from the attempt to load the library as a resource:
java.lang.NullPointerException: No resource found with name '/lib/libJCudaRuntime-apple-x86_64.jnilib'
    at jcuda.LibUtils.loadLibraryResource(LibUtils.java:149)
    at jcuda.LibUtils.loadLibrary(LibUtils.java:83)
    at jcuda.runtime.JCuda.initialize(JCuda.java:340)
    at jcuda.runtime.JCuda.<clinit>(JCuda.java:327)
    at org.mystic.cuda.JCudaRuntimeTest.main(JCudaRuntimeTest.java:13)
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no JCudaRuntime-apple-x86_64 in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at jcuda.LibUtils.loadLibrary(LibUtils.java:94)
    at jcuda.runtime.JCuda.initialize(JCuda.java:340)
    at jcuda.runtime.JCuda.<clinit>(JCuda.java:327)
    at org.mystic.cuda.JCudaRuntimeTest.main(JCudaRuntimeTest.java:13)
    at jcuda.LibUtils.loadLibrary(LibUtils.java:126)
    at jcuda.runtime.JCuda.initialize(JCuda.java:340)
    at jcuda.runtime.JCuda.<clinit>(JCuda.java:327)
    at org.mystic.cuda.JCudaRuntimeTest.main(JCudaRuntimeTest.java:13)

**Comment by MysterionRise** [comment]
Are you still interested in solving that problem? Cause I don't have any Mac device with Geforce graphics, I will need your help to solve that issue.

**Comment by zaurus1717** [comment]
Hi,
i'm very interested in the solution of the problem, because i have the same problem.

I don't know how to solve it :-(

**Comment by MysterionRise** [comment]
That's good. Could you give me more details what's going on? Since I don't have any kind of Mac Os system it's really hard for me to come with solution.

**Comment by zaurus1717** [comment]
I have downloaded the latest version of cuda 0.6.5 and mavenized-jcuda. I have identified the correct libraries for version 0.6.5 of JCuda MAC.
I use the script to install_libs.sh to position them correctly within the local repository.
When I try to build the project maven unfortunately does not find these libraries that are present instead. Instead with version 0.6.0 the build works correctly.
I hope you can help me even with this problem.

Moving on to the previous request I will update. I have a graphics card: "NVIDIA GeForce GT 650M 1024MB"
Using the 0.6.0 version of CUDA to run my application (in the system there is also the version 0.6.5). The project is compiled, but when it is made the first call to the "JCudaDriver.setExceptionsEnabled (true);"
an exception is thrown, that is:

Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Could not load the native library.
Error while loading native library "JCudaDriver-apple-x86_64" with base name "JCudaDriver"
Operating system name: Mac OS X
Architecture: x86_64
Architecture bit size: 64
Stack trace from the attempt to load the library as a resource:
java.lang.NullPointerException: No resource found with name '/lib/libJCudaDriver-apple-x86_64.jnilib'
at jcuda.LibUtils.loadLibraryResource (LibUtils.java:149)
at jcuda.LibUtils.loadLibrary (LibUtils.java:83)
at jcuda.driver.JCudaDriver. <clinit> (JCudaDriver.java:231)
....

I can not understand why he seeks libraries .jnilib in a folder that I never indicated. Moreover libraries JCUDA are not .jnilib but .dylib
I also tried to create a folder in the root called lib where I put the files .dylib. I have also tried to duplicate the libraries changing the extension in .jnilib , but the error is always the same.

**Comment by MysterionRise** [comment]
Oh, first of all - you don't need to run any sh scripts on your machine - its for me only.

Second - I got this Mac OS X libs from this site - http://jcuda.org/downloads/downloads.html
I'm not sure, that I got u - did 0.6.0 working on your machine?

**Comment by zaurus1717** [comment]
Hi thank you for your response.

I used the script, because in the latest version of mavenized-jcuda there were folders for libraries 0.6.5 but were not present libraries .dylib

I got the libraries, by - http://jcuda.org/downloads/downloads.html - for version 0.6.5
for version 0.6.0 instead libraries there were in your project.

Version 0.6.0 works only for the build, but at runtime (when calling the function that I told you), the exception is thrown

**Comment by MysterionRise** [comment]
Oh, I see. Let me update repo with 0.6.5 libs myself and then you could test it. It will be done this evening.

**Comment by zaurus1717** [comment]
Thanks for this update

Instead as regards the other problem? namely the fact that the exception is thrown with the version 0.6.0

**Comment by MysterionRise** [comment]
Just push 0.6.5 libs 

Problem about 0.6.0 and jnilib - it's still unclear to me

**Comment by zaurus1717** [comment]
Thanks for the new version.

Concerning the problem of the .jnilib libraries in version 0.6.0 I place my solution, so that if someone has the same problem can solve it, waiting for a definitive solution :)
I do not know if the problem involves mavenized-jcuda or JCUDA, do not really know. However I solved by changing the extension .dylib of the files placed in ./target/lib/ to .jnilib (after a build)
To automate my project and not always having to rename the files I did deploy in my local repository new renamed files, using the script ./install_lib. changing the final part of the commands in the following way
-Dclassifier = Apple-x86_64 -Dfile = libJCudaDriver-apple-x86_64.jnilib (-Dfile is different for each library;))

**Comment by MysterionRise** [comment]
So, you just rename them and it helps? I will appreciate a pull request from you and we could close the issue.

**Comment by MysterionRise** [comment]
Any news?

**Comment by yarenty** [comment]
Hi, Have the same issue:
No resource found with name '/lib/libJCudaRuntime-apple-x86_64.jnilib'

I think there are 2 issues:
 - instead 'jnilib' - there should be 'dylib' for Apple - this is in LibUtils.createLibExtension() 
 - in the lib directory there is 'libJCudaRuntime-mac-x86_64.dylib' should be: ibJCudaRuntime-apple-x86_64.dylib

I really like this mavenized version!

Cheers,
Jaro

**Comment by MysterionRise** [comment]
Hi, Jaroslaw!

Could you try to rename this lib in target/lib manually - will it execute
well? If yes, I will need to just add this renaming step.

Thanks,

**Comment by yarenty** [comment]
Not sure If I could help... as was trying few options and getting this through target/lib is not working

I run this code:
  
         System.out.println("Current dir:"+new java.io.File( "." ).getCanonicalPath());
         System.out.println("Current dir using System:" +System.getProperty("user.dir"));
         System.out.println("Current relative path is: " + Paths.get("").toAbsolutePath().toString());
    	
         //not working:
         // /lib/libJCudaRuntime-mac-x86_64.dylib
         // lib/libJCudaRuntime-mac-x86_64.dylib
         // ../lib/libJCudaRuntime-mac-x86_64.dylib
         // /../lib/libJCudaRuntime-mac-x86_64.dylib
        String resourceName = "/lib/libJCudaRuntime-apple-x86_64.jnilib";
		 
         String lbDir = LibUtils.class.getClassLoader().getResource("").getPath() ;
         System.out.println("LibUtil dir :" + lbDir);		 
		 
         URL lbUrl = LibUtils.class.getClassLoader().getResource(resourceName) ;
         System.out.println("LibUtil URL :" + lbUrl);
		 
	 InputStream inputStream = 
	                LibUtils.class.getResourceAsStream(resourceName);
	            if (inputStream == null)
	            {
	            	System.out.println( "No resource found with name '"+resourceName+"'");
	            }
    	

and output is :

Current dir:/Users/yarenty/cuda-workspace/jcuda
Current dir using System:/Users/yarenty/cuda-workspace/jcuda
Current relative path is: /Users/yarenty/cuda-workspace/jcuda
LibUtil dir :/Users/yarenty/cuda-workspace/jcuda/target/classes/
LibUtil URL :null
No resource found with name '/lib/libJCudaRuntime-apple-x86_64.jnilib'

I checked everything (what I think could be connected) - file permissions / calling path from shell - this seems to be working ... but not from java...

If you have any ideas - I can check it for you.


FYI: I manage to run everything smoothly when I put libraries to directory where DYLD_LIBRARY_PATH is pointing to:
/opt/cuda/libJCudaRuntime-apple-x86_64.dylib
(this is used in System.loadLibrary default behaviour).

**Comment by MysterionRise** [comment]
Btw, which version of Cuda you use?

**Comment by yarenty** [comment]
6.5 and as I said if I put it into library path - is working perfectly...

... which for me is great!

**Comment by MysterionRise** [comment]
Yeah, I understand, But in my opinion - it's not the idea of that project to put it inside library path, cause it's operation system specific.

**Comment by MysterionRise** [comment]
Closed due to time passed. Please use JCuda from Maven central
