### ISSUE TITLE
Power Linux (ppc64le) support

### ISSUE THREAD

**Issue by kiszk** [MysterionRise/mavenized-jcuda#8]
What is the process for adding support for additional platforms?

I have successfully built native libraries of 0.7.0.a for ppc64le (Ubuntu). Later, I would prepare them of 0.7.5.

**Comment by MysterionRise** [comment]
Interesting:-) That will require some work on my side - mainly check if
maven supports it and then add it. Will let you know about progress.

**Comment by MysterionRise** [comment]
@kiszk, you will help me a lot, if you could run

*mvn -version -X* on that ppc64le machine. Also, I would like to get this native libs

**Comment by kiszk** [comment]
Sure. As far as I know, the result of "arch" is different depends on JVM that we use.
How shouldI give you native libs? Can I create a pull request that includes naive libs?

```
$ cat /etc/debian_version 
jessie/sid
$ uname -a
Linux npk40ar 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:55:08 UTC 2014 ppc64le ppc64le ppc64le GNU/Linux
$ JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-ppc64el mvn --version -X
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_40-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-ppc64el/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-23-generic", arch: "ppc64", family: "unix"
$ JAVA_HOME=/opt/ibm/ibm-java-ppc64le-80SR1FP10 mvn --version -X
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0, vendor: IBM Corporation
Java home: /opt/ibm/ibm-java-ppc64le-80SR1FP10/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-23-generic", arch: "ppc64le", family: "unix"
$
```

**Comment by MysterionRise** [comment]
Yes, data you provided is just exactly what I need. Yes, create a pull request please.

I'm hoping that arch *ppc64* will do the trick, but will see, hope, that with your help we make it working on both version of jvm.

**Comment by MysterionRise** [comment]
@kiszk, I also add support for activation for ppc64le. Could you check it out?
